### ISSUE TITLE
Squawk

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/parrot-ruby#10]
Maybe this was intentional, but nowhere in the lesson or parrot.rb comments does it mention that the default phrase must be "Squawk!". That doesn't become clear until a user either checks the content of the test or runs Learn and sees the error message.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by AnnJohn** [comment]
@dougtebay Thanks for raising the issue. It should be fixed now.
