### ISSUE TITLE
"return" value

### ISSUE THREAD

**Issue by allensoberano** [learn-co-curriculum/parrot-ruby#11]
when running the test it should work with or without the word: return

It took me a while to figure out that you wanted that specific command in my rb file. I was suprised because the lessons have been stating that methods return your last expression. 

So if there is a way so it also accepts it without the "return"

def parrot(phrase="Squawk!")
  puts phrase
  phrase
end

**Comment by AnnJohn** [comment]
@allensoberano Thanks for raising this issue. Could you please explain a little bit more. It would be helpful if you could mention the specific files this issue affect and use screenshots or code snippets to reproduce your issue. Please explain what you were expecting to happen, what actually happened, and if you have a solution, then please detail that as well.

**Comment by allensoberano** [comment]
It seems to be working as expected now. Not sure if it was updated or something. All is good now! thanks

**Comment by AnnJohn** [comment]
@allensoberano Great! Glad it's working.
