### ISSUE TITLE
"local tests not run"

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/parrot-ruby#13]
The green light for having run local tests, won't light up.    
I did the lab 3 times, getting all tests green, using Learn and then Learn Submit.  

I also did it using clone/fork/add/push method.   

I've created 2 pull requests, but the "local tests button" on the Learn page is still not turning green.     I'll move to the next lesson for now.

**Comment by AnnJohn** [comment]
Hi @smithWEBtek this looks like a bug so could you please file a bug report? If you hover over your profile pic in Learn, you'll see the option to Report a Bug. 

Also for immediate help with this, you can use the Ask a Question tool in Learn and someone from our support team will help you right away. But a bug report will definitely be good to file.
