### ISSUE TITLE
Return Values Lab not connected to IDE correctly

### ISSUE THREAD

**Issue by tmetz** [learn-co-curriculum/parrot-ruby#18]
The Return Values Lab in the "Variables and Methods" section of Procedural Ruby is marked as a lab, opens a lab in IDE, but seems to operate as an informational lesson.  I get the "I'm done" button.  After I mark the lesson as done, it does seem to connect back and says "Completed This Lab."

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
