### ISSUE TITLE
The lab is lacking an indicator for "Fork", "Run", and "Submit".

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/parrot-ruby#19]
Excuse me for "parroting" the same issue, but somehow this lab has the "I'm Done" button (as though this were a README or Code-Along), instead of the "Fork", "Run", and "Submit" indicators. The rest of it still works properly.

Thank you for looking into this, and my apologies for the pun.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

**Comment by Sdcrouse** [comment]
Thank you! I will be sure to do that.

Sdcrouse
