### ISSUE TITLE
Issue showing parrot lesson as a completed lab

### ISSUE THREAD

**Issue by aljimenez5** [learn-co-curriculum/parrot-ruby#20]
I just completed the parrot-ruby lab but in my curriculum it doesn't show up as completed. It just looks like it is an article you press "done reading", instead of the usual "fork", "test", "submit.

<img width="1257" alt="screen shot 2018-08-05 at 10 33 12 am" src="https://user-images.githubusercontent.com/36483256/43686903-fea0c064-989a-11e8-974f-fb51a2ab35c5.png">

**Comment by cjbrock** [comment]
Hi @aljimenez5,
Once you've completed a lab, this is what it will look like! If you notice in the screenshot, it says that you've completed the lab, not a lesson. The three boxes will go away and you will only see one success box once you've completed all three stages of completing a lab. Congratulations on joining Learn, and I hope you enjoy becoming a developer as much as I have. <3
// Corinna

**Comment by aljimenez5** [comment]
Hi Corinna, thank you for getting back to me! I just checked again and it still isn’t registering as completed on my curriculum drop down. I feel there’s a disconnect from it saying “Lab Completed” and it actually registering as so. I hope that clarification makes sense.

**Comment by cjbrock** [comment]
That is odd! I'm actually showing it completed on my end. Either way, I wouldn't worry about it too much. If you feel like you understand the material, you should be fine.
