### ISSUE TITLE
Completed the Lab - Curriculum List Says I have Not Completed the Lab

### ISSUE THREAD

**Issue by austinpowell58** [learn-co-curriculum/parrot-ruby#21]
It's saying that the lab is complete, but it says it is not completed on my curriculum list. I've tried failing the test on purpose and re submitting the lab to pass the test in a different way. Can someone help fix this?

Thanks!

![image](https://user-images.githubusercontent.com/39357294/44065307-97351b96-9f2f-11e8-84c2-08ec097fa7d9.png)

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

**Comment by austinpowell58** [comment]
Sounds good sorry to bother you!

Appreciate your understanding.
